-- Human-friendly sequential order number shown in the UI. An identity column
-- backfills existing orders automatically (roughly creation order; the number
-- only needs to be unique + stable, not perfectly ordered).
-- ponytail: identity default is fine at this scale; switch to a formatted
-- sequence (e.g. ORD-YYYY-000001) only if the business needs it.
alter table public.orders
  add column if not exists order_number bigint generated by default as identity;

create unique index if not exists idx_orders_order_number
  on public.orders(order_number);

-- Re-expose order_number from the two read functions.
create or replace function public.order_json(p_order_id uuid)
returns jsonb
language sql stable
as $$
  select jsonb_build_object(
    'id', o.id,
    'order_number', o.order_number,
    'user_id', o.user_id,
    'total_amount', o.total_amount::text,
    'is_deleted', o.is_deleted,
    'created_at', o.created_at,
    'updated_at', o.updated_at,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', oi.id, 'product_id', oi.product_id, 'quantity', oi.quantity,
        'unit_price', oi.unit_price::text, 'is_deleted', oi.is_deleted,
        'created_at', oi.created_at
      ) order by oi.created_at)
      from order_items oi where oi.order_id = o.id), '[]'::jsonb),
    'modification_history', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', h.id, 'modification_type', h.modification_type, 'modified_at', h.modified_at,
        'item_id', h.item_id, 'user_id', h.user_id,
        'old_value', h.old_value, 'new_value', h.new_value
      ) order by h.modified_at desc)
      from order_modification_history h where h.order_id = o.id), '[]'::jsonb)
  )
  from orders o where o.id = p_order_id;
$$;

create or replace function public.list_orders(p_user_id uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_agg(row order by (row->>'created_at') desc), '[]'::jsonb)
  from (
    select jsonb_build_object(
      'id', o.id, 'order_number', o.order_number, 'user_id', o.user_id,
      'total_amount', o.total_amount::text,
      'is_deleted', o.is_deleted, 'created_at', o.created_at, 'updated_at', o.updated_at,
      'item_count', (select count(*) from order_items oi
                     where oi.order_id = o.id and oi.is_deleted = false)
    ) as row
    from orders o where o.user_id = p_user_id
  ) s;
$$;
